# Generated by Django 2.1.5 on 2019-02-09 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal', models.CharField(max_length=5)),
                ('flight_status', models.CharField(choices=[('AC', 'Awaiting check-in'), ('CO', 'Check-in is over'), ('C', 'Check-in'), ('R', 'Rejected'), ('D', 'Delayed'), ('B', 'Boarding'), ('GC', 'Gate closed'), ('F', 'In flight'), ('A', 'Arrived')], db_index=True, default=('AC', 'Awaiting check-in'), max_length=20)),
                ('gate', models.CharField(blank=True, db_index=True, max_length=5, null=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.Flight')),
            ],
            options={
                'db_table': 'timeline',
            },
        ),
    ]
