# Generated by Django 2.1.5 on 2019-02-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(db_index=True, max_length=12, unique=True)),
                ('country', models.CharField(max_length=15)),
                ('load_capacity', models.PositiveSmallIntegerField()),
                ('fuel_capacity', models.PositiveSmallIntegerField()),
                ('passengers_capacity', models.PositiveSmallIntegerField(db_index=True)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'planes',
            },
        ),
    ]
