# Generated by Django 2.1.5 on 2019-02-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='caption',
            field=models.TextField(),
        ),
    ]
